### ISSUE TITLE
Collection ready for review

### ISSUE THREAD

**Issue by amyjoui** [uidaholib/collectionbuilder-cdm-template#100]
- [ ] Idaho Forester (forester)
I wasn't able to use the objectid include feature to bring in an image from a different collection into the About page, so I put in the Bootstrap wording instead, which worked but then I couldn't figure out how to center the images to the text. Everything else seemed to work and merge/update OK. @dcnb @evanwill @owikle

**Comment by dcnb** [comment]
updated @amyjoui 

I just added <div class="text-center"> around the included figure code and that centered it. Good photos!!!
