### ISSUE TITLE
sticky top for about nav menu?

### ISSUE THREAD

**Issue by dcnb** [uidaholib/collectionbuilder-cdm-template#101]
https://www.lib.uidaho.edu/digital/arbornotes/about.html

Check it out. What do you think @evanwill and @owikle? Is this sustainable. Was easy to set up. If you like it/think it will work, I'll add it to the master.

**Comment by evanwill** [comment]
Fine (but not overly excited or not about it :shrug: ). 
Seems to work okay on mobile. It isn't supported on IE and some mobile browsers, but in this context I think it will degrade without any issues and still look fine, just not be sticky. 

It has class `sticky sticky-top`, but only `sticky-top` is necessary? I don't think `sticky` is anything.

and shouldn't the drop shadow be increased like 500%? :laughing:
