### ISSUE TITLE
Issue with Browse page 

### ISSUE THREAD

**Issue by dcnb** [uidaholib/collectionbuilder-cdm-template#102]
if you include an apostrophe in the search, it breaks and won't search past the apostrophe. 

Is this a problem in the CB releases as well, @evanwill ?  I'm assuming we need to escape the phrase or something like that ...

**Comment by evanwill** [comment]
Sorry, I can't reproduce it? 
Can you be more specific and give the example?

I gave three items the subjects `Evan`, `Evan's test`, and `Evan's dog` respectively. 
If I search `Evan` you get three items, ``Evan's` you get two,  `Evan's test` you get one.
The urls and links are escaped properly.

**Comment by evanwill** [comment]
I do find that `'` and fancy `’` are different characters which could be frustrating, but doesn't break the search

**Comment by evanwill** [comment]
@dcnb follow up info??

**Comment by dcnb** [comment]
I can't seem to recreate it either. Must have been a fancy character?
