### ISSUE TITLE
Ready for review!

### ISSUE THREAD

**Issue by amyjoui** [uidaholib/collectionbuilder-cdm-template#104]
- [x] University of Idaho Historical Photos (spec_uihp)
I had a lot of troubles with the compound objects, but I think I finally got it corrected. The only thing that I can still see that is wrong, and I have no idea how to fix it, is the little symbol for compound objects in the objects card on the home page. 
@dcnb @evanwill @owikle

**Comment by owikle** [comment]
@amyjoui don't forget to delete the old configuration csvs from the _data folder. Looks good otherwise, thanks!

**Comment by amyjoui** [comment]
Thanks Olivia! Good to know, Michelle said it was possible to delete those, but I was erring on the side of not getting rid of something that may be important later on. I'll start removing the old with my next collection.

________________________________
