### ISSUE TITLE
Collection update

### ISSUE THREAD

**Issue by kitstokes** [uidaholib/collectionbuilder-cdm-template#116]
@owikle @dcnb @evanwill 

- [ ] phs, Potlatch Historical Society Collection is ready for review

**Comment by owikle** [comment]
@kitstokes don't forget to update the Data section of theme.yml with the metadata fields. Also, try zooming out on the map--there's an object out in the middle of the pacific ocean and it's supposed to be in Idaho... check the lat and long and let me know when it's fixed, I'll put it up!

**Comment by kitstokes** [comment]
@owikle I fixed the lat and long of the one item! I also copy and pasted in the metadata fields from phs.csv into the Data section on theme.yml, but it didn't look like it changed anything so let me know if it's still not done correctly.

**Comment by owikle** [comment]
Looks good, thanks! I already fixed the data section so that's why you didn't see any difference. It's up now.
