### ISSUE TITLE
cities-new

### ISSUE THREAD

**Issue by evanwill** [uidaholib/collectionbuilder-cdm-template#126]
@mshannon95 @dcnb I noticed the growing About page on cities-new branch-- I was thinking that would make a good "Glossary" style feature. Rather than writing out a huge About which is going to get cumbersome and hard to add nav--maybe all that content should go into a CSV--then we can generate pages for each city, which can display the descriptions you have created for each and pull in all the related image items.

Let me know, I can quickly convert your current About page into a Sheet easily!

**Comment by mshannon95** [comment]
@evanwill @dcnb Everything currently written on the About page was written last spring, and after looking at it again this week, I was planning to scrap what's there and replace it with a general overview of Idaho state history. The cities that I already have feel like they could use more work, and even if I left them as is, I don’t think I have time to finish the rest of the cities in the next couple weeks. Creating a glossary for the cities would be cool and useful, I just don't think I can devote the time it requires to be good and not look like someone rushed through it. Maybe this would be a good long-term project for a Spec student worker to build on what I have and do more in-depth research, and in the meantime my overview of Idaho state history could be the About page. What are your thoughts?

**Comment by evanwill** [comment]
@mshannon95 that makes sense now! 
I like the idea of the glossary style Cities even if there isn't content for every town--I will just transform what you have into a CSV and we can use it if desired at some point in the *future*.
