### ISSUE TITLE
font updates

### ISSUE THREAD

**Issue by evanwill** [uidaholib/collectionbuilder-cdm-template#128]
merge updates from main and deploy to server: 

- [x] main
- [x] aerial
- [x] aers
- [x] arbornotes
- [x] archivalidaho      
- [x] argonautphotos     
- [x] barstock
- [x] bigburn
- [x] boxing
- [x] bunkerhill
- [x] calnon
- [x] cattle
- [x] cccidaho
- [x] chatcolab
- [x] cities
- [x] crbproj
- [x] dodson
- [x] dworshak
- [x] etd
- [x] expforsav
- [x] familytree
- [x] fisher
- [x] football
- [x] forester
- [x] forestryresearch
- [x] fwres
- [x] guidedreading
- [x] higgins
- [x] hwhi
- [x] iddings
- [x] iftnc
- [x] ijcdg
- [x] iwdl
- [x] jazzfest
- [x] laughlin
- [x] lcheritage
- [x] lchsphotos
- [x] lewistonorch
- [x] lfc
- [x] marsh
- [x] mccall
- [x] nwpostcards
- [x] ott
- [x] pg1
- [x] pg2
- [x] phs
- [x] plcphotos
- [x] priestlake
- [x] psychiana
- [x] rangecoll
- [x] riegger
- [x] sanborn
- [x] sbw
- [x] shattuck
- [x] spec_hm
- [x] spec_kic
- [x] spec_pot
- [x] spec_uihp
- [x] stonebraker
- [x] transitions
- [x] treesgrewtall
- [x] troosevelt
- [x] uiext
- [x] vandalvideo
- [x] watkins
- [x] whitepine
- [x] womenscenter

**Comment by evanwill** [comment]
@owikle we should use this to clean up unused branches. what is some of these???

**Comment by evanwill** [comment]
pg1 is up, https://www.lib.uidaho.edu/digital/pg1/ is that supposed to be added to all collections?

**Comment by owikle** [comment]
I thought we talked about this today! Hold off, I'm already going through them.

**Comment by owikle** [comment]
Ah, ok. PG1's not supposed to be up. It's the same content as this: https://www.lib.uidaho.edu/digital/campus/. Not sure when that happened, I'll take it down for now.

**Comment by evanwill** [comment]
i know it is same items, but /pg1/ is a bit more fully functional that /campus/ right now!

**Comment by owikle** [comment]
Should we switch them and just plan to add in the map features later?

**Comment by evanwill** [comment]
not sure... just didn't know it was a think (or forgot)!
