### ISSUE TITLE
item page next/prev

### ISSUE THREAD

**Issue by evanwill** [uidaholib/collectionbuilder-cdm-template#17]
add to breadcrumbs, check on mobile

**Comment by owikle** [comment]
Would you rather the arrows be added to the breadcrumbs or be taken off completely? I changed it so that now when the screen is small the arrow buttons disappear. But I can add them to the breadcrumbs instead if that's what you had in mind.

**Comment by evanwill** [comment]
Just hidden on small is good. I think the breadcrumbs ended up to crowded
with the arrows added. Thanks
