### ISSUE TITLE
rewrite browse

### ISSUE THREAD

**Issue by evanwill** [uidaholib/collectionbuilder-cdm-template#27]
- [x] handle hidden text in search (see sandborn)
- [x] as javascript
- [ ] add gallery option

**Comment by evanwill** [comment]
rewrite in js

- [ ] browse filter js script
- [ ] rewrite is url query rather than hash
- [ ] rewrite hash urls that point to it

**Comment by evanwill** [comment]
@dcnb and @owikle check out the draft version of js based browse on branch `browse-js`

it doesn't seem insanely faster, but actually benchmarked on big collections it cuts the filter time in half. the biggest difference will be when clicking on a subject in the "Subjects" page and coming to the browse page--on the current browse it has to load all items, then filter and rerender--the browse-js page it filters first and just renders the filtered stuff, so much faster. 

however, what I realized is more than half the time is not the filtering--thats pretty fast--it is the re-rendering of all the elements on the page. So basically to make it faster than browse-js, we actually need to simplify the bootstrap classes on the cards--or do something to paginate or infinite load the items rather than just adding them all at once. That is probably fairly do-able, just adding more of the cards to the screen as you scroll down, which would probably cut the time down again by half.

**Comment by dcnb** [comment]
@evanwill right now just checking it, the load seems at least 10 x faster than it was. It's definitely a usable, non-noticeable time, which is AWESOME. It does look like you got rid of the buttons and some other elements on the cards. Does that improve the load time a great deal too? I prefer infinite load to paginate -- think that will be easier in the longrun for other users too. 

Good work EVAN! Am I looking at the wrong thing though? You say it doesn't seem insanely faster but from my vantage, comparing the browse-js.html to the cccidaho on the library server and also compare the two pages on my laptop server, the new version does seem insanely faster. 

Maybe we should just hire you as the developer for the grant ...

**Comment by evanwill** [comment]
@dcnb, ha ha, i don't know, it seemed a lot faster, but not insanely fast... :man_shrugging: 

yeah there is a couple more things to implement, like subject buttons (since the subject buttons are just links they don't impact load times) and type--those just require a couple more `if`s in the code, and change the configuration file a bit.
