### ISSUE TITLE
help

### ISSUE THREAD

**Issue by owikle** [uidaholib/collectionbuilder-cdm-template#37]
@evanwill I tried to update my forked repo with your latest commits but accidentally ended up merging my changes to this branch. I'm getting confused with the revert process. Can you help? Sorry!

**Comment by evanwill** [comment]
I'll send you an email, but you just need to revert the merge commit (not the individual commits):

`git revert -m 1 d98f5e41153b1fb5afbd8c2d6900c719a1b5d6ab`

71829f054533638c44efcfafad3f3e298020671c

although this merge didn't really mess anything up!
