### ISSUE TITLE
browse function - view in order

### ISSUE THREAD

**Issue by mshannon95** [uidaholib/collectionbuilder-cdm-template#74]
Hi,
When I go into a collection in Collection Builder, and I go into the Browse tab, the images are not in numeric order based on Identification Number. Is it possible to add an option to view the images in order based on their Identification Numbers? I understand the randomness can help showcase different facets of the collection and that's fine, but it would also be nice to have an option to view the images in their correct arrangement (a.k.a. the arrangement that reflects their physical arrangement in our physical collections).

Thank you!! - Michelle Shannon

**Comment by evanwill** [comment]
@mshannon95 thanks for the input, i appreciate it-- 
It is possible--it was that way, we switched to randomizing (just as you mention) to surface more of the collection to users. However, we do hope to add a button to allow user to select sorting order at some point. I will let you know when I get a chance to work on!

**Comment by dcnb** [comment]
@evanwill @owikle  I added a sort button to the new branch that sorts on any option listed in config-browse that isn't a button. It's amazing. You're welcome. Now we just need to update all the collections. @evanwill you will do at least 5!

**Comment by evanwill** [comment]
I cleaned up a bit of the markup so that it doesn't interfere with other dropdowns, but still has some issues: 
1. if any item in the set does NOT have a value for the field, than sort doesn't work
2. something seems to be making it slower than without it, which I can't see why exactly yet, but it seems like it is ending up doing everything twice in a row.

**Comment by dcnb** [comment]
#1 -- fake news
#2 -- fake news. It is the fastest ever!

**Comment by dcnb** [comment]
Also, this was moved to the updates to CB branch from the one you just
edited, so you should go edit that one too.

**Comment by evanwill** [comment]
ugg.. okay.
@dcnb i took another quick look and 1. is true (I don't exactly understand it, but items without a field just like get left in their original place in the array somehow? its odd),
2. everything seems correct--but still has an odd slow unresponsiveness when you click the dropdown--i don't get it either...
