### ISSUE TITLE
use of Rights box

### ISSUE THREAD

**Issue by evanwill** [uidaholib/collectionbuilder-cdm-template#80]
currently the item page has the "Rights" box which is not configurable. 
It is automatically added if an item has a field named "rights" and/or "rightsstatement".

Looking at collections, a lot of metadata has these fields named random other things, including many recently done use "rights (standardized)", so rights box doesn't show up. Also, many config-metadata contain both the rights fields, so the item page displays the rights fields, then also includes the rights box. 

Do we want to normalize this better? Just have one or the other? Make sure everyone actually changes the field names, and doesn't add them to config-metadata?

**Comment by dcnb** [comment]
I've noticed this as well. I'd like to normalize this -- I had forgotten
how it worked until talking to Michelle the other day.

??: Do you think we could build in code that said, if field contains
"rights" put it in the rights box and (separately) if field contains
rights, don't put it in the regular portion. Could be useful for GH too.

leads to more questions though: like do we require user to list the field
in config-metadata--I can see folks being annoyed that a rights field
appears. For us, the code solution might work though.

We can also just make folks more generally aware ...

**Comment by owikle** [comment]
Might be good to also have people also change the field names now anyway (I thought this was in your instructions already), since they already have to edit cdmid and objectid fields when merging.

**Comment by evanwill** [comment]
add a bit of logic to skip metadata display of rights if it will show up in box below @evanwill

**Comment by evanwill** [comment]
conclusion:
- be sure to update metadata to have standard names of `rights` and/or `rightsstatement`.
- `rightsstatement` should be in config-metadata so that it can be mapped for markup. It doesn't need a display_name, since it will automatically be added to the rights box. `rightsstatement,,,DCTERMS.rights,license` 
- Even if you add a display name, it skips it in the main metadata area, and puts it in the rights box. 

611b2de035efb71ff31eec4151fe681435f606f6
