### ISSUE TITLE
about/collection updates

### ISSUE THREAD

**Issue by dcnb** [uidaholib/collectionbuilder-cdm-template#84]
Ready for review and move to web server (from Michelle): 
- [x] psychiana
- [x] Potlatch Lumber Company (plcphotos)
- [x] Columbia River Basin Project (crbproj)

**Comment by dcnb** [comment]
updated crbproj ---> couple notes we'll go over in meeting tomorrow @mshannon95 
 
- watch out for pages created before; your revision left off pbs video page and locations page
- subjects could still be edited to make the cloud better

I also edited the about page some to add a little more structure to the presentation. Lot of trial and error there. 

Overall it's a great update, and I think a needed change of title. About information is intriguing.

**Comment by dcnb** [comment]
- [ ] Psychian
- [ ] other collection

**Comment by dcnb** [comment]
@dcnb  @owikle

**Comment by mshannon95** [comment]
@dcnb when you say "subjects could still be edited to make the cloud better," do you mean in the metadata sheet? Using the Getty Art & Architecture subjects?

**Comment by dcnb** [comment]
yeah. This is an old collection, so we used lcsh and subjects idiosyncratic to the collection. AAT would be great, but really, I think just chunking these up would work well for our visualizations. So doing a find/replace on the '--' within the lcsh and replacing those with ';' -- then consolidating or eliminating some of the subjects. Basically, they're too long!

**Comment by evanwill** [comment]
@mshannon95 have you ever used OpenRefine? it's great for cleaning up subjects--you would probably love it :wink: (let me know if you want to meet about it)

**Comment by mshannon95** [comment]
@evanwill nope I've never used OpenRefine! I would love to meet about it if you're willing to give me a quick Zoom tutorial!

**Comment by dcnb** [comment]
@mshannon95 I updated this yesterday. Spent a good deal of time on the Psychiana about page and incorporated the stylistic changes into the master branch. Psychiana is a good model for the use of a variety of techniques, so might be something you copy for reference onto your computer. Thank you for all this work. It's hard to keep up with you!
