### ISSUE TITLE
Collection Update

### ISSUE THREAD

**Issue by amyjoui** [uidaholib/collectionbuilder-cdm-template#94]
- [ ] Idaho Historical Aerial Photographs (aerial)
Merged to reflect current Master. Everything was working when I checked it last. Added Sections to the About page, but left the metadata-facets-fields as they were. Please let me know if I forgot anything or if there is anything else!
@dcnb @evanwill @owikle

**Comment by evanwill** [comment]
@dcnb is there any reason for the [Gemfile](https://github.com/uidaholib/collectionbuilder-cdm-template/blob/aerial/Gemfile) you added to this branch? It is trying to install jekyll from the git source, and not part of master?

**Comment by dcnb** [comment]
No, I don't think so. That might have been a workaround for the issues
before Jekyll was updated. Can definitely be removed.

**Comment by evanwill** [comment]
thanks!

**Comment by evanwill** [comment]
this is updated, thanks
https://www.lib.uidaho.edu/digital/aerial/
